# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Diaspora"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Hugo-theme-diaspora"
homepage = "https://diaspora.hojun.cn/"
tags = ["blog", "ajax", "simple", "responsive", "clean"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "hojun"
  homepage = "https://www.hojun.cn"

# If porting an existing theme
[original]
  name = "Diaspora"
  homepage = "https://isujin.com/"
  repo = "https://github.com/LoeiFy/Diaspora"
